<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 4.8.4
 */

/**
 * Database `classicmodels`
 */

/* `classicmodels`.`customers` */
$customers = array(
  array('customerNumber' => '103','customerName' => 'Atelier graphique','contactLastName' => 'Schmitt','contactFirstName' => 'Carine ','phone' => '40.32.2555','addressLine1' => '54, rue Royale','addressLine2' => NULL,'city' => 'Nantes','state' => NULL,'postalCode' => '44000','country' => 'France','salesRepEmployeeNumber' => '1370','creditLimit' => '21000.00'),
  array('customerNumber' => '112','customerName' => 'Signal Gift Stores','contactLastName' => 'King','contactFirstName' => 'Jean','phone' => '7025551838','addressLine1' => '8489 Strong St.','addressLine2' => NULL,'city' => 'Las Vegas','state' => 'NV','postalCode' => '83030','country' => 'USA','salesRepEmployeeNumber' => '1166','creditLimit' => '71800.00'),
  array('customerNumber' => '114','customerName' => 'Australian Collectors, Co.','contactLastName' => 'Ferguson','contactFirstName' => 'Peter','phone' => '03 9520 4555','addressLine1' => '636 St Kilda Road','addressLine2' => 'Level 3','city' => 'Melbourne','state' => 'Victoria','postalCode' => '3004','country' => 'Australia','salesRepEmployeeNumber' => '1611','creditLimit' => '117300.00'),
  array('customerNumber' => '119','customerName' => 'La Rochelle Gifts','contactLastName' => 'Labrune','contactFirstName' => 'Janine ','phone' => '40.67.8555','addressLine1' => '67, rue des Cinquante Otages','addressLine2' => NULL,'city' => 'Nantes','state' => NULL,'postalCode' => '44000','country' => 'France','salesRepEmployeeNumber' => '1370','creditLimit' => '118200.00'),
  array('customerNumber' => '121','customerName' => 'Baane Mini Imports','contactLastName' => 'Bergulfsen','contactFirstName' => 'Jonas ','phone' => '07-98 9555','addressLine1' => 'Erling Skakkes gate 78','addressLine2' => NULL,'city' => 'Stavern','state' => NULL,'postalCode' => '4110','country' => 'Norway','salesRepEmployeeNumber' => '1504','creditLimit' => '81700.00'),
  array('customerNumber' => '124','customerName' => 'Mini Gifts Distributors Ltd.','contactLastName' => 'Nelson','contactFirstName' => 'Susan','phone' => '4155551450','addressLine1' => '5677 Strong St.','addressLine2' => NULL,'city' => 'San Rafael','state' => 'CA','postalCode' => '97562','country' => 'USA','salesRepEmployeeNumber' => '1165','creditLimit' => '210500.00'),
  array('customerNumber' => '125','customerName' => 'Havel & Zbyszek Co','contactLastName' => 'Piestrzeniewicz','contactFirstName' => 'Zbyszek ','phone' => '(26) 642-7555','addressLine1' => 'ul. Filtrowa 68','addressLine2' => NULL,'city' => 'Warszawa','state' => NULL,'postalCode' => '01-012','country' => 'Poland','salesRepEmployeeNumber' => NULL,'creditLimit' => '0.00'),
  array('customerNumber' => '128','customerName' => 'Blauer See Auto, Co.','contactLastName' => 'Keitel','contactFirstName' => 'Roland','phone' => '+49 69 66 90 2555','addressLine1' => 'Lyonerstr. 34','addressLine2' => NULL,'city' => 'Frankfurt','state' => NULL,'postalCode' => '60528','country' => 'Germany','salesRepEmployeeNumber' => '1504','creditLimit' => '59700.00'),
  array('customerNumber' => '129','customerName' => 'Mini Wheels Co.','contactLastName' => 'Murphy','contactFirstName' => 'Julie','phone' => '6505555787','addressLine1' => '5557 North Pendale Street','addressLine2' => NULL,'city' => 'San Francisco','state' => 'CA','postalCode' => '94217','country' => 'USA','salesRepEmployeeNumber' => '1165','creditLimit' => '64600.00'),
  array('customerNumber' => '131','customerName' => 'Land of Toys Inc.','contactLastName' => 'Lee','contactFirstName' => 'Kwai','phone' => '2125557818','addressLine1' => '897 Long Airport Avenue','addressLine2' => NULL,'city' => 'NYC','state' => 'NY','postalCode' => '10022','country' => 'USA','salesRepEmployeeNumber' => '1323','creditLimit' => '114900.00'),
  array('customerNumber' => '141','customerName' => 'Euro+ Shopping Channel','contactLastName' => 'Freyre','contactFirstName' => 'Diego ','phone' => '(91) 555 94 44','addressLine1' => 'C/ Moralzarzal, 86','addressLine2' => NULL,'city' => 'Madrid','state' => NULL,'postalCode' => '28034','country' => 'Spain','salesRepEmployeeNumber' => '1370','creditLimit' => '227600.00'),
  array('customerNumber' => '144','customerName' => 'Volvo Model Replicas, Co','contactLastName' => 'Berglund','contactFirstName' => 'Christina ','phone' => '0921-12 3555','addressLine1' => 'Berguvsvägen  8','addressLine2' => NULL,'city' => 'Luleå','state' => NULL,'postalCode' => 'S-958 22','country' => 'Sweden','salesRepEmployeeNumber' => '1504','creditLimit' => '53100.00'),
  array('customerNumber' => '145','customerName' => 'Danish Wholesale Imports','contactLastName' => 'Petersen','contactFirstName' => 'Jytte ','phone' => '31 12 3555','addressLine1' => 'Vinbæltet 34','addressLine2' => NULL,'city' => 'Kobenhavn','state' => NULL,'postalCode' => '1734','country' => 'Denmark','salesRepEmployeeNumber' => '1401','creditLimit' => '83400.00'),
  array('customerNumber' => '146','customerName' => 'Saveley & Henriot, Co.','contactLastName' => 'Saveley','contactFirstName' => 'Mary ','phone' => '78.32.5555','addressLine1' => '2, rue du Commerce','addressLine2' => NULL,'city' => 'Lyon','state' => NULL,'postalCode' => '69004','country' => 'France','salesRepEmployeeNumber' => '1337','creditLimit' => '123900.00'),
  array('customerNumber' => '148','customerName' => 'Dragon Souveniers, Ltd.','contactLastName' => 'Natividad','contactFirstName' => 'Eric','phone' => '+65 221 7555','addressLine1' => 'Bronz Sok.','addressLine2' => 'Bronz Apt. 3/6 Tesvikiye','city' => 'Singapore','state' => NULL,'postalCode' => '079903','country' => 'Singapore','salesRepEmployeeNumber' => '1621','creditLimit' => '103800.00'),
  array('customerNumber' => '151','customerName' => 'Muscle Machine Inc','contactLastName' => 'Young','contactFirstName' => 'Jeff','phone' => '2125557413','addressLine1' => '4092 Furth Circle','addressLine2' => 'Suite 400','city' => 'NYC','state' => 'NY','postalCode' => '10022','country' => 'USA','salesRepEmployeeNumber' => '1286','creditLimit' => '138500.00'),
  array('customerNumber' => '157','customerName' => 'Diecast Classics Inc.','contactLastName' => 'Leong','contactFirstName' => 'Kelvin','phone' => '2155551555','addressLine1' => '7586 Pompton St.','addressLine2' => NULL,'city' => 'Allentown','state' => 'PA','postalCode' => '70267','country' => 'USA','salesRepEmployeeNumber' => '1216','creditLimit' => '100600.00'),
  array('customerNumber' => '161','customerName' => 'Technics Stores Inc.','contactLastName' => 'Hashimoto','contactFirstName' => 'Juri','phone' => '6505556809','addressLine1' => '9408 Furth Circle','addressLine2' => NULL,'city' => 'Burlingame','state' => 'CA','postalCode' => '94217','country' => 'USA','salesRepEmployeeNumber' => '1165','creditLimit' => '84600.00'),
  array('customerNumber' => '166','customerName' => 'Handji Gifts& Co','contactLastName' => 'Victorino','contactFirstName' => 'Wendy','phone' => '+65 224 1555','addressLine1' => '106 Linden Road Sandown','addressLine2' => '2nd Floor','city' => 'Singapore','state' => NULL,'postalCode' => '069045','country' => 'Singapore','salesRepEmployeeNumber' => '1612','creditLimit' => '97900.00'),
  array('customerNumber' => '167','customerName' => 'Herkku Gifts','contactLastName' => 'Oeztan','contactFirstName' => 'Veysel','phone' => '+47 2267 3215','addressLine1' => 'Brehmen St. 121','addressLine2' => 'PR 334 Sentrum','city' => 'Bergen','state' => NULL,'postalCode' => 'N 5804','country' => 'Norway  ','salesRepEmployeeNumber' => '1504','creditLimit' => '96800.00'),
  array('customerNumber' => '168','customerName' => 'American Souvenirs Inc','contactLastName' => 'Franco','contactFirstName' => 'Keith','phone' => '2035557845','addressLine1' => '149 Spinnaker Dr.','addressLine2' => 'Suite 101','city' => 'New Haven','state' => 'CT','postalCode' => '97823','country' => 'USA','salesRepEmployeeNumber' => '1286','creditLimit' => '0.00'),
  array('customerNumber' => '169','customerName' => 'Porto Imports Co.','contactLastName' => 'de Castro','contactFirstName' => 'Isabel ','phone' => '(1) 356-5555','addressLine1' => 'Estrada da saúde n. 58','addressLine2' => NULL,'city' => 'Lisboa','state' => NULL,'postalCode' => '1756','country' => 'Portugal','salesRepEmployeeNumber' => NULL,'creditLimit' => '0.00'),
  array('customerNumber' => '171','customerName' => 'Daedalus Designs Imports','contactLastName' => 'Rancé','contactFirstName' => 'Martine ','phone' => '20.16.1555','addressLine1' => '184, chaussée de Tournai','addressLine2' => NULL,'city' => 'Lille','state' => NULL,'postalCode' => '59000','country' => 'France','salesRepEmployeeNumber' => '1370','creditLimit' => '82900.00'),
  array('customerNumber' => '172','customerName' => 'La Corne D\'abondance, Co.','contactLastName' => 'Bertrand','contactFirstName' => 'Marie','phone' => '(1) 42.34.2555','addressLine1' => '265, boulevard Charonne','addressLine2' => NULL,'city' => 'Paris','state' => NULL,'postalCode' => '75012','country' => 'France','salesRepEmployeeNumber' => '1337','creditLimit' => '84300.00'),
  array('customerNumber' => '173','customerName' => 'Cambridge Collectables Co.','contactLastName' => 'Tseng','contactFirstName' => 'Jerry','phone' => '6175555555','addressLine1' => '4658 Baden Av.','addressLine2' => NULL,'city' => 'Cambridge','state' => 'MA','postalCode' => '51247','country' => 'USA','salesRepEmployeeNumber' => '1188','creditLimit' => '43400.00')
);
